# Generated by Django 5.1.5 on 2025-01-24 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_caregiver_availability_type_and_more'),
        ('booking', '0002_alter_appointment_duration_alter_appointment_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('session_type', models.CharField(choices=[('emergency', 'Emergency Consultation'), ('followup', 'Follow-up Consultation'), ('routine', 'Routine Checkup')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('meet_link', models.URLField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caregiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='account.caregiver')),
                ('pregnant_woman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='account.pregnantwoman')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
