# Generated by Django 5.1.5 on 2025-01-25 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_idverification'),
        ('booking', '0003_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='pregnant_woman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='account.pregnantwoman'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('routine', 'Routine'), ('emergency', 'Emergency'), ('follow_up', 'Follow Up')], default='routine', max_length=20),
        ),
    ]
