# Generated by Django 5.1.5 on 2025-01-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_pregnantwoman_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiver',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
