# Generated by Django 5.1.5 on 2025-01-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_caregiver_experience_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='availability_type',
            field=models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('weekends', 'Weekends Only')], default='full-time', max_length=20),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='service_radius',
            field=models.PositiveIntegerField(default=10, help_text='Maximum distance willing to travel (in km)'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
