# Generated by Django 5.1.5 on 2025-01-24 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_caregiver_availability_type_caregiver_service_radius_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caregiver',
            name='availability_type',
        ),
        migrations.RemoveField(
            model_name='caregiver',
            name='service_radius',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pincode',
        ),
    ]
