# Generated by Django 5.1.5 on 2025-01-25 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_caregiver_availability_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('passport', 'Passport'), ('drivers_license', "Driver's License"), ('national_id', 'National ID'), ('aadhar', 'Aadhar Card')], max_length=20)),
                ('id_number', models.CharField(max_length=50)),
                ('id_front_image', models.ImageField(upload_to='id_verifications/')),
                ('id_back_image', models.ImageField(upload_to='id_verifications/')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ID Verification',
                'verbose_name_plural': 'ID Verifications',
            },
        ),
    ]
